[package]
name = "vbspview"
version = "0.1.0"
edition = "2021"

[dependencies]
three-d = "0.10.2"
vbsp = { version = "0.1.0", path = "../bsp" }
miette = { version = "3.2.0", features = ["fancy"] }
thiserror = "1.0.30"
delaunator = "1.0.1"

[profile.dev.package."*"]
opt-level = 2