[package]
name = "vbspview"
version = "0.1.0"
edition = "2021"
authors = ["Robin Appelman <robin@icewind.nl>"]
license = "MIT"

[dependencies]
#three-d = { version = "0.16.3", features = ["egui-gui"] }
three-d = { version = "0.16.3", features = ["egui-gui"], path = "../rust/three-d" }
three-d-asset = { version = "0.6" }
vbsp = { version = "0.2.0", git = "https://github.com/icewind1991/vbsp" }
#vbsp = { version = "0.2.0", path = "../bsp" }
miette = { version = "5.5.0", features = ["fancy"] }
thiserror = "1.0.37"
delaunator = "1.0.1"
itertools = "0.10.5"
steamlocate = "=2.0.0-alpha.0"
vpk = "0.2.0"
vmdl = { version = "*", git = "https://github.com/icewind1991/vmdl" }
#vmdl = { version = "*", path = "../vmdl" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.2"
cgmath = "0.18.0"
tf-demo-parser = { version = "0.4.0", git = "https://github.com/demostf/parser" }
steamid-ng = "1.0.0"
clap = { version = "4.0.29", features = ["derive"] }
splines = { version = "4.1.1", features = ["cgmath"] }
vtf = "0.1.6"
vmt-parser = { version = "0.1", git = "https://github.com/icewind1991/vmt-parser" }
image = "0.23.14"

[profile.dev.package."*"]
opt-level = 2

[features]
dump_materials = []